config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  
  resources :articles
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    #@article = Article.new
  end
  
  def create
    #render plain: params[:article].inspect
    @article = Article.new(params.require(:article).permit(:title, :text))
 
    @article.save
    redirect_to @article
  end
  
  def show
    @article =Article.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<h1>This is new in article</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Getaccepted</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
	<% end %>
	<!-- Links for sign up, login etc -->
	<p class="navbar-text pull-right">
		<% if user_signed_in? %>
  			Logged in as <strong><%= current_user.email %></strong>.
			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
  			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
	</p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello GetAccepted</h1>
<p>We started and we are going to achieve the peak. Ths is for you Sayali...</p>
<%=link_to "New Article", new_article_path%>